# WHY NUMPY?
### Numpy is used for performing numerical operations like array additions, Subtarction, Multiplication

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
scores=[95,96,98,99,90,95,33,35]

In [6]:
arr=np.array([95,96,98,99,90,95,33,35])

In [7]:
arr

array([95, 96, 98, 99, 90, 95, 33, 35])

In [8]:
arr+2

array([ 97,  98, 100, 101,  92,  97,  35,  37])

# LIST VS ARRAY

### List cannot perform element-wise operations whereas array can perform element-wise operations

### List are Heteregenous and Arrays are Homogenous

In [9]:
scores_1=[90,80.5,60]

In [10]:
scores_1

[90, 80.5, 60]

In [11]:
scores_2=[90,40,60]

In [12]:
scores_2

[90, 40, 60]

In [13]:
arr=np.array([90,60,45.5,85,80])

In [14]:
arr

array([90. , 60. , 45.5, 85. , 80. ])

In [15]:
arr_1=np.array([50,40,'80',45])

In [16]:
arr_1

array(['50', '40', '80', '45'], dtype='<U21')

## Array calculation are fast in Nature

### Now Creation of 1D Array

In [17]:
arr_1=np.array([1,2,3,4,5,6,7,8,9])

In [18]:
arr_1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr_1.ndim

1

In [ ]:
## Creation of 2D Array

In [20]:
arr_2=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [23]:
arr_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
arr_2.ndim

2

## Creation of 3D Array

In [28]:
arr_3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [29]:
arr_3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [30]:
arr_3.ndim

3

In [35]:
arr_4=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11.0,12]])

In [36]:
arr_4

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [37]:
arr_4.ndim

2

In [38]:
arr_4[2][1]=np.nan

In [39]:
arr_4

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7., nan,  9.],
       [10., 11., 12.]])

In [40]:
arr_4[3][1]=np.nan

In [41]:
arr_4

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7., nan,  9.],
       [10., nan, 12.]])

In [42]:
arr_4[3]=np.nan

In [43]:
arr_4

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7., nan,  9.],
       [nan, nan, nan]])

In [44]:
arr_5=np.array([1,2,3,4,5,6,7,8,9,90])

In [45]:
arr_5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 90])

In [46]:
arr_5.mean()

np.float64(13.5)

In [47]:
arr_5.max()

np.int64(90)

In [48]:
arr_5.min()

np.int64(1)

In [49]:
arr_5.std()

np.float64(25.617376914898998)

In [50]:
arr_5.sort()

In [51]:
arr_5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 90])

In [53]:
arr_5.argmax()   #It gives us index number of the maximun number.

np.int64(9)

In [54]:
arr_5=np.array([1,2,3,4,5,6,7,8,9,90,1000])

In [55]:
arr_5.max()

np.int64(1000)

In [56]:
arr_5.argmax()

np.int64(10)

In [57]:
arr_5.argmin()

np.int64(0)

In [59]:
arr_5.cumsum()  #Cummulative_sum

array([   1,    3,    6,   10,   15,   21,   28,   36,   45,  135, 1135])

In [60]:
arr_4.flatten()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7., nan,  9., nan, nan, nan])

In [61]:
arr_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [63]:
arr_2.flatten()  #is converting 2D to 1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr_2.ndim

2

In [65]:
np.linspace(1,11,50)

array([ 1.        ,  1.20408163,  1.40816327,  1.6122449 ,  1.81632653,
        2.02040816,  2.2244898 ,  2.42857143,  2.63265306,  2.83673469,
        3.04081633,  3.24489796,  3.44897959,  3.65306122,  3.85714286,
        4.06122449,  4.26530612,  4.46938776,  4.67346939,  4.87755102,
        5.08163265,  5.28571429,  5.48979592,  5.69387755,  5.89795918,
        6.10204082,  6.30612245,  6.51020408,  6.71428571,  6.91836735,
        7.12244898,  7.32653061,  7.53061224,  7.73469388,  7.93877551,
        8.14285714,  8.34693878,  8.55102041,  8.75510204,  8.95918367,
        9.16326531,  9.36734694,  9.57142857,  9.7755102 ,  9.97959184,
       10.18367347, 10.3877551 , 10.59183673, 10.79591837, 11.        ])

In [66]:
np.arange(1,21,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [67]:
np.random.rand(10,5)

array([[0.80851801, 0.43957619, 0.50086674, 0.64825784, 0.66944474],
       [0.83531376, 0.63713453, 0.08776175, 0.40795597, 0.07244651],
       [0.22670034, 0.99604055, 0.89099972, 0.68032312, 0.61805954],
       [0.04853574, 0.12763977, 0.70647358, 0.05585042, 0.5513011 ],
       [0.90336039, 0.20269269, 0.11860442, 0.12475394, 0.519827  ],
       [0.42604385, 0.63534023, 0.79876424, 0.90766735, 0.6946157 ],
       [0.37017895, 0.10771504, 0.17529629, 0.57339139, 0.50632252],
       [0.57217789, 0.0779802 , 0.81980584, 0.258839  , 0.09826619],
       [0.0214237 , 0.37242231, 0.53408656, 0.12831737, 0.59911126],
       [0.15887786, 0.18153521, 0.98907939, 0.73116803, 0.3270362 ]])

In [74]:
np.random.seed(18)
np.random.rand(10,5)

array([[0.65037424, 0.50545337, 0.87860147, 0.18184023, 0.85223307],
       [0.75013629, 0.66610167, 0.98789545, 0.25696842, 0.02830593],
       [0.63571912, 0.84731239, 0.73617463, 0.02080711, 0.11160313],
       [0.29772374, 0.68697019, 0.86162606, 0.19863436, 0.65718903],
       [0.69965563, 0.35239247, 0.78996055, 0.81404794, 0.19742128],
       [0.94945529, 0.47660039, 0.66660035, 0.21131204, 0.80752632],
       [0.31968612, 0.29393597, 0.30191818, 0.8278894 , 0.55253369],
       [0.1916774 , 0.71425674, 0.63987036, 0.53320383, 0.57252791],
       [0.01233254, 0.69523798, 0.53465921, 0.07913472, 0.0136375 ],
       [0.27785304, 0.99738528, 0.22560064, 0.10501535, 0.01630078]])

In [76]:
np.random.randint(1,101,60)

array([17, 54, 48, 85, 20, 71, 15,  2, 11, 36, 83, 21, 69, 81, 15, 73, 99,
       37,  6, 93, 23, 29, 87, 94, 11, 77, 24, 24, 80, 20, 94, 51, 88, 81,
       67, 33,  6, 55, 67, 17, 47, 74, 54, 74, 78,  3, 28, 38, 21, 76, 32,
       68, 28, 97, 24, 20, 79, 60, 81, 23], dtype=int32)

In [78]:
np.random.randn(1,101,60)   #It included negative numbers also.

array([[[-0.42975276, -1.01235989, -0.45183507, ...,  2.14651824,
         -0.66152095, -0.04215528],
        [-3.91896235,  0.79471896, -0.40671969, ...,  0.96211894,
         -2.07447687,  0.09210157],
        [ 0.23815331,  2.40766106,  0.42662187, ...,  0.84874357,
         -0.1944843 , -1.00575259],
        ...,
        [ 1.55297928, -0.23567349, -0.52719685, ...,  0.65902452,
         -1.57252239, -1.04672557],
        [-0.75395073,  0.9711578 ,  1.304302  , ...,  0.1113674 ,
         -0.50233426,  1.54271466],
        [ 0.13356616, -0.91320739,  2.88824589, ...,  0.36453385,
          0.95711557, -0.91353329]]])

In [80]:
np.random.randint(1,60,60)

array([10, 31,  9,  6, 21, 33, 57, 55, 42, 12, 11, 54, 31,  5, 44, 16, 57,
       27, 39,  3, 14, 21, 55, 47, 21, 17, 37, 45, 47, 44, 56,  1, 15, 57,
       35, 23, 12, 41, 25,  7, 29, 53, 10, 41, 43, 35, 53, 50, 36, 30, 35,
       55, 24, 41,  4, 15, 31, 53, 43, 37], dtype=int32)